
ARGS:
 tab: 'test'
 GPUS: 0 
 multi_person: True
 kernel_sizes: [5]
 use_coordmaps: True
 fine_tune: True
 eval: False

 baseline: 'hrnetv5'
 input_size: 512
 centermap_size: 64
 model_precision: 'fp32'
 val_batch_size: 1
 nw: 4
 gmodel_path: '../trained_models/pw3d_81.8_58.6.pkl' #'../trained_models/CenterHMR+CAR.pkl'

 video_or_frame: True
 input_video_path: '../demo/sample_video.mp4' # None
 webcam_mesh_color: 'ghostwhite'  #'LightCyan'
 save_mesh: False
 save_centermap: False
 save_dict_results: False
 webcam: False
 multiprocess: False
