
ARGS:
 tab: 'V1_resnet_pw3d_ft'
 dataset: 'crowdpose,pw3d'
 GPUS: 0,1,2,3
 distributed_training: False
 model_version: 1
 epoch: 1

 master_batch_size: -1
 val_batch_size: 64
 batch_size: 64
 nw: 6
 nw_eval: 2
 lr: 0.00005
 adjust_lr_factor: 0.2

 fine_tune: True
 fix_backbone_training_scratch: False
 match_preds_to_gts_for_supervision: True
 eval: False
 supervise_global_rot: False
 calc_PVE_error: True

 model_return_loss: True
 collision_aware_centermap: True
 collision_factor: 0.2
 homogenize_pose_space: False
 shuffle_crop_mode: False
 shuffle_crop_ratio_2d: 0.1
 shuffle_crop_ratio_3d: 0.2

 merge_smpl_camera_head: False
 head_block_num: 2

 backbone: 'resnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2

 model_path: trained_models/ROMP_ResNet50_V1.pkl

loss_weight:
  MPJPE: 200.
  PAMPJPE: 360.
  P_KP2D: 400.
  Pose: 80.
  Shape: 6.
  Prior: 1.6
  CenterMap: 160.

sample_prob:
 crowdpose: 0.2
 pw3d: 0.8